export const MODES = {
  READ_ONLY: 'READ_ONLY',
  EDITING: 'EDITING',
  DRAW_POINT: 'DRAW_POINT',
  DRAW_PATH: 'DRAW_PATH',
  DRAW_POLYGON: 'DRAW_POLYGON',
  DRAW_RECTANGLE: 'DRAW_RECTANGLE',
  DRAW_RECTANGLE_ONE_CLICK: 'DRAW_RECTANGLE_ONE_CLICK',
  MEASURE_DISTANCE: 'MEASURE_DISTANCE',
  MEASURE_AREA: 'MEASURE_AREA',
};
